steps:
  - id: eu.gcr.io/$PROJECT_ID/postgresql-streamer-go
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go
      - -t
      - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go
      - -f
      - Dockerfile
      - .
    waitFor: ['-']
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go
      - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go:$TAG_NAME

images:
  - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go
  - eu.gcr.io/$PROJECT_ID/postgresql-streamer-go:$TAG_NAME

timeout: 1800s
