name: Release
on:
  push:
    tags:
      - '*'
jobs:
  asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build artifacts
        run: make build extract-from-image
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: bin/postgresql-streamer*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  cloudbuild:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: GCP Cloud Build
#        uses: docker://docker.io/itscaro/github-actions-gcloud # prebuilt image of https://github.com/actions/gcloud/tree/master/cli
#        with:
#          entrypoint: .github/cloudbuild.sh
#        env:
#          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
#          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
#          TAG_NAME: ${{ github.ref }}
